version: '3.7'
services:

  auto_groups:
    build:
      context: .
      args:
        - SERVER_HOST=${SERVER_HOST}
        - SERVER_PORT=${SERVER_PORT}
        - VERSION=${VERSION}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
