version: '3.7'
services:

  auto_groups:
    build:
      context: .
      args:
        - SERVER_HOST=${SERVER_HOST}
        - SERVER_PORT=${SERVER_PORT}
        - VERSION=${VERSION}
        - SOFTWAREDEPOT_URL=${SOFTWAREDEPOT_URL}
        - SOFTWAREDEPOT_USER=${SOFTWAREDEPOT_USER}
        - SOFTWAREDEPOT_PASS=${SOFTWAREDEPOT_PASS}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env